
development:
  adapter:  sqlite3
  database: db/soomo-mbus-development.sqlite3
  pool:     5
  timeout:  5000

test:
  adapter:  sqlite3
  database: db/soomo-mbus-test.sqlite3
  pool:     5
  timeout:  5000

production:
  adapter:  sqlite3
  database: db/soomo-mbus-production.sqlite3
  pool:     5
  timeout:  5000
